[package]
name = "board_gen"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "board_gen"
path = "main.rs"

[dependencies]
anyhow = "1"
game = { path = "../../crates/game" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"